### ISSUE TITLE
Discard the search tree when go to the next step?

### ISSUE THREAD

**Issue by Macheng2016** [JuliaPOMDP/POMCPOW.jl#6]
Hi, zsunberg,

I have a question about POMCPOW which is not discussed in your paper (I think): when we have finished the planning and took an actual action, we received an observation from the environment (which would be different from all the simulated observations during the tree search). In discrete observation case, it is likely that the actual observation is the same as one of the observations we encountered during the tree search, so we can reuse that branch. But in continuous observation case, is there a principled way to reuse some branches? Thanks!

Best,
Macheng

**Comment by zsunberg** [comment]
Hi Macheng, Thanks for your question! I do not know of an easy way to reuse parts of the tree when the true observation doesn't match a simulated observation exactly.

We didn't think too hard about this and didn't discuss it in the paper because, in our experience reusing parts of the tree offered little practical advantage. This is because, unless the number of potentially optimal actions is small and the number of likely observations is small, only a very small part of the tree is re-used.

Hope that helps! Let me know if it doesn't make sense!

**Comment by Macheng2016** [comment]
Thank you for the explanation!

Best,
Macheng
